### ISSUE TITLE
omg-cli -error- gcp-service-broker

### ISSUE THREAD

**Issue by sabarivs** [cf-platform-eng/gcp-pcf-quickstart#1]
I am getting below error when i trigger deploy script
omg-cli: error: accepting EULA for gcp-service-broker: accepting eula for gcp-service-broker, 5563, recieved: 404 Not Found, try --help

when i did initial analysis of code , version of gcp-service-broker(3.4.1) is not available in the pivotal network. please refer below file
gcp-pcf-quickstart/blob/master/src/omg-cli/omg/tiles/service_broker/resource.go

is there any fix for this issue?

Regards
Sabari

**Comment by johnsonj** [comment]
Thanks @sabarivs ! Agree with your analysis there. Fix inbound.
