### ISSUE TITLE
nat.tf boot disk image is out of date

### ISSUE THREAD

**Issue by z0331** [cf-platform-eng/gcp-pcf-quickstart#18]
The current nat.tf configuration currently includes:
```
boot_disk {
    initialize_params {
      image = "debian-cloud/debian-8"
      size  = 10
    }
```

It looks like the debian-8 image family is now deprecated and causes the deploy script to fail with `* google_compute_instance.nat: Error resolving image name 'debian-gnu/linux-8': Could not find image or family debian-gnu/linux-8`.

I think this should be updated to `debian-cloud/debian-9`.

**Comment by evandbrown** [comment]
https://github.com/cf-platform-eng/gcp-pcf-quickstart/commit/e928689faceea4c1c0f0d9368b7482485a59208d
