### ISSUE TITLE
Update Service Broker Version

### ISSUE THREAD

**Issue by josephlewis42** [cf-platform-eng/gcp-pcf-quickstart#29]
The quickstart needs to update the GCP service broker version to be the most recent one.

With the upgrade, it can delete the default plans it was creating in 
https://github.com/cf-platform-eng/gcp-pcf-quickstart/blob/master/src/omg-cli/omg/tiles/service_broker/configuration.go#L39 because all of those services now have pre-defined plans.

**Comment by boparp-pivotal** [comment]
@josephlewis42 work is in progress to update this quickstart to PCF v2.3 and GCP Service Broker to the latest v4.0.0
