### ISSUE TITLE
omg-cli: error: Timeout waiting for Ops Manager to start, try --help

### ISSUE THREAD

**Issue by pnatraj** [cf-platform-eng/gcp-pcf-quickstart#7]
Hi  johnson

Thank you very much for the great documentation i did follow the same and when the deployment goes through half a stage i get this below error please can you help.

vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS9zZG4tZTEwMjYwOGQlNDB3aXByby1hM3MuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K
sys_domain = sys.pcf-demo.com
tcp_domain = tcp.pcf-demo.com
tcp_port_range = 1024-65535
tcp_router_pool = pcf-cf-tcp
vm_tag = omg-no-ip
wss_router_pool = pcf-cf-wss

~/gcp-pcf-quickstart
[jumpbox] WARNING: ignoring SSH certificate issue for 104.196.39.27:22
[jumpbox] mkdir -p ~/"keys"
[jumpbox] uploading file /tmp/tile514800179 as omg-cli
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/keys/jumpbox_ssh.pub as keys/jumpbox_ssh.pub
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/terraform_output.json as terraform_output.json
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/config.json as config.json
[jumpbox] running command ~/omg-cli push-tiles --env-dir=$PWD

waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
omg-cli: error: Timeout waiting for Ops Manager to start, try --help
omg-cli: error: running command: Process exited with status 1, try --help
nataraj_purudappa@wipro-a3s:~/gcp-pcf-quickstart$ eout waiting for Ops Manager to start, try --help

**Comment by pnatraj** [comment]
Same issue with delete, but the delete process did continue to delete the VM's and other objects.

delete deployment in /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf (y/n)? y
begin delete
[jumpbox] WARNING: ignoring SSH certificate issue for 104.196.39.27:22
[jumpbox] mkdir -p ~/"keys"
[jumpbox] uploading file /tmp/tile289346450 as omg-cli
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/keys/jumpbox_ssh.pub as keys/jumpbox_ssh.pub
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/terraform_output.json as terraform_output.json
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/config.json as config.json
[jumpbox] running command ~/omg-cli delete-installation --env-dir=$PWD
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
omg-cli: error: Timeout waiting for Ops Manager to start, try --help
omg-cli: error: running command: Process exited with status 1, try --help
deleteDirectorVM: deleted 0 VMs
~/gcp-pcf-quickstart/src/omg-tf ~/gcp-pcf-quickstart
random_id.ops_manager_password_generator: Refreshing state... (ID: bGFLqnnERfaUdynlV8OsqA)
random_id.credhub_key_name_generator: Refreshing state... (ID: -ncbWQ)
random_id.db-name: Refreshing state... (ID: -LKSnB7I5-8)
random_id.opsman_db_username: Refreshing state... (ID: EwJ9eKwvjOs)
random_id.db-name: Refreshing state... (ID: 8pxn5NlBESc)
random_id.opsman_db_password: Refreshing state... (ID: pcpbRdBJwNXJuvr_XHXYSdTzvklXDJCQAnMRgxpMTf8)
random_id.stackdriver_nozzle_account: Refreshing state... (ID: 4QJgjQ)
random_id.service_broker_password: Refreshing state... (ID: B5oSkLpDRlWGMNjieuZdTcb1sJc--Y2jdeNnZEHGje0)
random_id.service_broker_account: Refreshing state... (ID: 8A-CtQ)
random_id.ops_manager_account: Refreshing state... (ID: uS1NFA)
random_id.credhub_key_generator: Refreshing state... (ID: e9Wt8nB1KfS8i6K8S4RtQDuLB6s)
random_id.ert_db_username: Refreshing state... (ID: g4ypP3uN2XQ)
random_id.service_broker_username: Refreshing state... (ID: qD4pVIKrH0o)
random_id.suffix: Refreshing state... (ID: p9LwvQ)
random_id.ops_manager_decryption_phrase_generator: Refreshing state... (ID: CsCJcr_WOBAhQnzWK9JciA)
random_id.ert_db_password: Refreshing state... (ID: B6r6WmRDOBh7NU25V-bm5JI8adNpsI_9GzKjw6wPwAk)
google_compute_target_pool.cf-wss: Refreshing state... (ID: pcf-cf-wss)
google_compute_image.ops-manager-image: Refreshing state... (ID: pcf-ops-manager-image)
google_compute_target_pool.cf-ssh: Refreshing state... (ID: pcf-cf-ssh)
google_compute_address.ops-manager-external: Refreshing state... (ID: projects/wipro-a3s/regions/us-east1/addresses/pcf-ops-manager)
google_compute_http_health_check.cf-tcp: Refreshing state... (ID: pcf-cf-tcp)
google_compute_address.cf-ssh: Refreshing state... (ID: projects/wipro-a3s/regions/us-east1/addresses/pcf-cf-ssh)
google_compute_instance_group.httplb[1]: Refreshing state... (ID: us-east1-c/pcf-httpslb-us-east1-c)
google_compute_address.jumpbox: Refreshing state... (ID: projects/wipro-a3s/regions/us-east1/addresses/pcf-jumpbox)
google_compute_ssl_certificate.cert: Refreshing state... (ID: pcf-lbcert20180214083203087000000001)
google_compute_address.cf-tcp: Refreshing state... (ID: projects/wipro-a3s/regions/us-east1/addresses/pcf-cf-tcp)
google_compute_network.pcf-network: Refreshing state... (ID: pcf-pcf-network)
google_compute_http_health_check.cf-public: Refreshing state... (ID: pcf-cf-public)
google_compute_global_address.cf: Refreshing state... (ID: pcf-cf)
google_compute_address.cf-wss: Refreshing state... (ID: projects/wipro-a3s/regions/us-east1/addresses/pcf-cf-wss)
google_compute_instance_group.httplb[2]: Refreshing state... (ID: us-east1-d/pcf-httpslb-us-east1-d)
google_compute_instance_group.httplb[0]: Refreshing state... (ID: us-east1-b/pcf-httpslb-us-east1-b)
google_sql_database_instance.master: Refreshing state... (ID: pcf--lksnb7i5-8)
...
...
...
oogle_compute_address.ops-manager-external: Destruction complete after 11s
google_compute_subnetwork.management-subnet: Destruction complete after 11s
google_compute_network.pcf-network: Destroying... (ID: pcf-pcf-network)
google_compute_image.ops-manager-image: Destruction complete after 11s
module.external_database.google_sql_database_instance.master: Still destroying... (ID: pcf--lksnb7i5-8, 1m10s elapsed)
google_compute_network.pcf-network: Still destroying... (ID: pcf-pcf-network, 10s elapsed)
module.external_database.google_sql_database_instance.master: Still destroying... (ID: pcf--lksnb7i5-8, 1m20s elapsed)
module.external_database.google_sql_database_instance.master: Destruction complete after 1m23s
module.external_database.random_id.db-name: Destroying... (ID: -LKSnB7I5-8)
module.external_database.random_id.db-name: Destruction complete after 0s
google_compute_network.pcf-network: Destruction complete after 18s

Destroy complete! Resources: 101 destroyed.
~/gcp-pcf-quickstart

**Comment by johnsonj** [comment]
Can you verify your domain is setup with Google Cloud DNS? ([docs](https://github.com/cf-platform-eng/gcp-pcf-quickstart/blob/master/docs/dns.md))

The sys_domain/tcp_domain output looks wrong unless you've parked the `pcf-demo.com` domain on Google Cloud DNS as the zone `pcf-zone`. If that was the case- I'd expect to see a Google Cloud DNS server here:

```
$ dig pcf-demo.com +short NS
ns-1330.awsdns-38.org.
ns-1607.awsdns-08.co.uk.
ns-195.awsdns-24.com.
ns-669.awsdns-19.net.
```

**Comment by pnatraj** [comment]
The domain is registered with AWS and the zone is configured in AWS and hence the names are resolved by AWS DNS servers.

**Comment by pnatraj** [comment]
I have udpated NS and SOA records in AWS Route 53 to the Google DNS servers, i shall give it a try and update the bug with the findings.

dig pcf-demo.com +short NS
ns-cloud-a1.googledomains.com.
ns-cloud-a2.googledomains.com.
ns-cloud-a4.googledomains.com.
ns-cloud-a3.googledomains.com.

Thanks
Nataraj

**Comment by johnsonj** [comment]
You can setup a subdomain (eg `gcp.pcf-demo.com`) and point it do a Cloud DNS Zone. See the [docs](https://github.com/cf-platform-eng/gcp-pcf-quickstart/blob/master/docs/dns.md).

**Comment by johnsonj** [comment]
(ops wrong button :), let me know how it goes!

Since your environment is in a strange state I recommend running the delete script until all looks good then deploying again.

**Comment by pnatraj** [comment]
Sure, i shall try and update it.

**Comment by pnatraj** [comment]
i think the clean up did not happen as expected..

google_sql_database_instance.service_brokeoogle_sql_database_instance.service_broker: Still creating... (6m30s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (6m30s elapsed)
google_sql_database_instance.service_broker: Still creating... (6m40s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (6m40s elapsed)
google_sql_database_instance.service_broker: Still creating... (6m50s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (6m50s elapsed)
google_sql_database_instance.service_broker: Still creating... (7m0s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (7m0s elapsed)
google_sql_database_instance.service_broker: Still creating... (7m10s elapsed)
google_sql_database_instance.service_broker: Still creating... (7m20s elapsed)
google_sql_database_instance.service_broker: Creation complete after 7m24s (ID: pcf-tiqsqadx3fe)
google_sql_user.service_broker: Creating...
  instance: "" => "pcf-tiqsqadx3fe"
  name:     "" => "Z1P36V23r5E"
  password: "<sensitive>" => "<sensitive>"
  project:  "" => "<computed>"
google_sql_user.service_broker: Still creating... (10s elapsed)
google_sql_user.service_broker: Creation complete after 17s (ID: pcf-tiqsqadx3fe/Z1P36V23r5E)
google_sql_database.uaa: Creating...
  charset:   "" => "<computed>"
  collation: "" => "<computed>"
  instance:  "" => "pcf-tiqsqadx3fe"
  name:      "" => "servicebroker"
  project:   "" => "<computed>"
  self_link: "" => "<computed>"
google_sql_database.uaa: Still creating... (10s elapsed)
google_sql_database.uaa: Creation complete after 11s (ID: pcf-tiqsqadx3fe:servicebroker)
Error: Error applying plan:
1 error(s) occurred:
r: Still creating... (6m30s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (6m30s elapsed)
google_sql_database_instance.service_broker: Still creating... (6m40s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (6m40s elapsed)
google_sql_database_instance.service_broker: Still creating... (6m50s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (6m50s elapsed)
google_sql_database_instance.service_broker: Still creating... (7m0s elapsed)
module.external_database.google_sql_database_instance.master: Still creating... (7m0s elapsed)
google_sql_database_instance.service_broker: Still creating... (7m10s elapsed)
google_sql_database_instance.service_broker: Still creating... (7m20s elapsed)
google_sql_database_instance.service_broker: Creation complete after 7m24s (ID: pcf-tiqsqadx3fe)
google_sql_user.service_broker: Creating...
  instance: "" => "pcf-tiqsqadx3fe"
  name:     "" => "Z1P36V23r5E"
  password: "<sensitive>" => "<sensitive>"
  project:  "" => "<computed>"
google_sql_user.service_broker: Still creating... (10s elapsed)
google_sql_user.service_broker: Creation complete after 17s (ID: pcf-tiqsqadx3fe/Z1P36V23r5E)
google_sql_database.uaa: Creating...
  charset:   "" => "<computed>"
  collation: "" => "<computed>"
  instance:  "" => "pcf-tiqsqadx3fe"
  name:      "" => "servicebroker"
  project:   "" => "<computed>"
  self_link: "" => "<computed>"
google_sql_database.uaa: Still creating... (10s elapsed)
google_sql_database.uaa: Creation complete after 11s (ID: pcf-tiqsqadx3fe:servicebroker)
Error: Error applying plan:
1 error(s) occurred:


 module.external_database.google_sql_database_instance.master: 1 error(s) occurred:
* google_sql_database_instance.master: Error, attempting to list users associated with instance pcf-9w4svlxty5s: googleapi: Error 503: Service temporarily unavailable.,
 serverException
Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

**Comment by pnatraj** [comment]
umpbox] WARNING: ignoring SSH certificate issue for  *****
[jumpbox] mkdir -p ~/"keys"
[jumpbox] uploading file /tmp/tile591959226 as omg-cli
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/keys/jumpbox_ssh.pub as keys/jumpbox_ssh.pub
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/terraform_output.json as terraform_output.json
[jumpbox] uploading file /home/nataraj_purudappa/gcp-pcf-quickstart/env/pcf/config.json as config.json
[jumpbox] running command ~/omg-cli push-tiles --env-dir=$PWD
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
....
....
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
waiting for Ops Manager to start
omg-cli: error: Timeout waiting for Ops Manager to start, try --help
omg-cli: error: running command: Process exited with status 1, try --help

**Comment by johnsonj** [comment]
The `Error 503: Service temporarily unavailable` error is a retriable error. You can repeat the command safely. 

Your DNS doesn't look right:
```
$ dig opsman.pcf-demo.com +short
<empty>
$ dig tcp.pcf-demo.com +short
35.227.178.174
```

Does the NS records you setup (ns-cloud-a{1,2,3,4].googledomains.com} match the rrdatas for this command?
```
gcloud dns record-sets list --zone=pcf-zone --format=flattened --filter="type=NS"
```

**Comment by pnatraj** [comment]
The delete script did clean up the dns recods, those records where there when i ran it,Sure i shall create the records an re-run it.

**Comment by pnatraj** [comment]
yes i suppose please below is the output of the command.

nataraj_purudappa@wipro-a3s:~/gcp-pcf-quickstart$ gcloud dns record-sets list --zone=pcf-zone --format=flattened --filter="type=NS"
---
kind:       dns#resourceRecordSet
name:       pcf-demo.com.
rrdatas[0]: ns-cloud-a1.googledomains.com.
rrdatas[1]: ns-cloud-a2.googledomains.com.
rrdatas[2]: ns-cloud-a3.googledomains.com.
rrdatas[3]: ns-cloud-a4.googledomains.com.
ttl:        21600
type:       NS
nataraj_purudappa@wipro-a3s:~/gcp-pcf-quickstart$

**Comment by johnsonj** [comment]
That looks good! If `deploy_pcf.sh` fails again try running `dig opsman.pcf-demo.com` and see if it resolves properly. You can also try to access it: `https://opsman.pcf-demo.com`

**Comment by pnatraj** [comment]
Sure i shall try and udpate.

**Comment by pnatraj** [comment]
The scripts fails with the same error as mentioned in comment 1

**Comment by johnsonj** [comment]
It looks like DNS propagation is taking too long and Cloud Shell and the jumpbox have a more aggressive cache then your local machine. 

Try to run `deploy_pcf.sh`, let it fail, then run it again 30mins-1hr later. The script is able to pick up where it left off and that should give it time for DNS propagation.

I'll see what sort of DNS flushing options could be baked into the script.

**Comment by pnatraj** [comment]
Thank you very much for your time and help, Sure i shall try and update.

**Comment by johnsonj** [comment]
Thanks for your patience @pnatraj - looks like we're resolved on the gcp-pcf-quickstart front. I'm not sure there is a blanket fix for the DNS propagation delay but maybe someone who knows more about it can offer a solution. 

I haven't experienced this issue when using this script with Cloud DNS but I've never used a root domain. I've always had a Cloud DNS Zone mapped to pcf.<my-domain>.com. Maybe that's related.
