### ISSUE TITLE
Awwvision: Sample application is not listing any images

### ISSUE THREAD

**Issue by pnatraj** [cf-platform-eng/gcp-pcf-quickstart#9]
I was able to deploy the sample application and am able to access it as well but i dont see any images in the bucket nor in the application.

nataraj_purudappa@wipro-a3s:~/gcp-pcf-quickstart/docs/samples/awwvision$ cf restart awwvision
Restarting app awwvision in org dev / space dev as admin...
Stopping app...
Waiting for app to start...
name:              awwvision
requested state:   started
instances:         1/1
usage:             1G x 1 instances
routes:            awwvision-delightful-oribi.apps.pcf-demo.com
last uploaded:     Thu 15 Feb 05:54:38 IST 2018
stack:             cflinuxfs2
buildpack:         client-certificate-mapper=1.4.0_RELEASE container-security-provider=1.11.0_RELEASE
                   java-buildpack=v4.7.1-offline-https://github.com/cloudfoundry/java-buildpack.git#6a3361a java-main java-opts java-security
                   jvmkill-agent=1.12.0_RELEASE open-jdk...
start command:     JAVA_OPTS="-agentpath:$PWD/.java-buildpack/open_jdk_jre/bin/jvmkill-1.12.0_RELEASE=printHeapHistogram=1 -Djava.io.tmpdir=$TMPDIR
                   -Djava.ext.dirs=$PWD/.java-buildpack/container_security_provider:$PWD/.java-buildpack/open_jdk_jre/lib/ext
                   -Djava.security.properties=$PWD/.java-buildpack/java_security/java.security $JAVA_OPTS" &&
                   CALCULATED_MEMORY=$($PWD/.java-buildpack/open_jdk_jre/bin/java-buildpack-memory-calculator-3.10.0_RELEASE -totMemory=$MEMORY_LIMIT -stackThreads=300
                   -loadedClasses=16228 -poolType=metaspace -vmOptions="$JAVA_OPTS") && echo JVM Memory Configuration: $CALCULATED_MEMORY && JAVA_OPTS="$JAVA_OPTS
                   $CALCULATED_MEMORY" && SERVER_PORT=$PORT eval exec $PWD/.java-buildpack/open_jdk_jre/bin/java $JAVA_OPTS -cp $PWD/.
                   org.springframework.boot.loader.JarLauncher
     state     since                  cpu    memory         disk           details
#0   running   2018-02-15T00:41:43Z   0.0%   310.7M of 1G   148.5M of 1G
nataraj_purudappa@wipro-a3s:~/gcp-pcf-quickstart/docs/samples/awwvision$

**Comment by johnsonj** [comment]
Did you click on the `Update with latest images` link from the web app? I believe it routes you to `/reddit` which causes the app to populate with images.

**Comment by pnatraj** [comment]
Apologies for not being clear,

1) I log into the application http://awwvision-delightful-oribi.apps.pcf-demo.com/
2) I click on Update with latest images (http://awwvision-delightful-oribi.apps.pcf-demo.com/reddit)
     Output  Scrape completed, View Images.
3) I click back on View Images.
    Output: Blank Page ( Only link visible is Update with latest images)

Note : Even after waiting for more than few minutes the results are the same.
          Please feel free to access the application http://awwvision-delightful-oribi.apps.pcf-demo.com/

**Comment by johnsonj** [comment]
Thanks! I can reproduce the issue with your URL. Do you see any errors from the app? `cf logs --recent awwvision` should show errors if they're present.

It could very well be a change in the Reddit API or unexpected response that's tripping up the app. I'll be out of office till next week so I may not be able to provide much help.

**Comment by pnatraj** [comment]
please you could do it when you get time.

nataraj_purudappa@wipro-a3s:~$ cf logs --recent awwvision
Retrieving logs for app awwvision in org dev / space dev as admin...

   2018-02-16T08:54:49.91+0530 [RTR/0] OUT awwvision-delightful-oribi.apps.pcf-demo.com - [2018-02-16T03:24:49.757+0000] "GET / HTTP/1.1" 200 0 2121 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.94 Safari/537.36" "130.211.3.221:53459" "10.0.4.24:61028" x_forwarded_for:"199.116.169.254, 35.201.88.241, 130.211.3.221" x_forwarded_proto:"http" vcap_request_id:"4be2df8c-b107-4830-4beb-65c0b3c6877b" response_time:0.154014152 app_id:"5a19546c-f10a-41e7-aca9-03c261da3886" app_index:"0" x_b3_traceid:"4423e3183e9f8ddd" x_b3_spanid:"4423e3183e9f8ddd" x_b3_parentspanid:"-"
   2018-02-16T08:54:49.91+0530 [RTR/0] OUT

**Comment by johnsonj** [comment]
I can repro your issue. The following error is repeated when hitting the `/reddit` endpoint:

```
   2018-02-20T15:05:26.06-0800 [APP/PROC/WEB/0] OUT 2018-02-20 23:05:26.068  WARN 14 --- [nio-8080-exec-1] c.g.c.s.awwvision.RedditScraper          : Issue in streaming image https://i.redditmedia.com/4xFezp8qybWigpg6WN5gkAuI39AIPdv4jdHijFU4_ns.jpg?fm=jpg&amp;s=70b7febedc4d774786e11226a4bbca8d
   2018-02-20T15:05:26.06-0800 [APP/PROC/WEB/0] OUT java.io.IOException: Server returned HTTP response code: 403 for URL: https://i.redditmedia.com/4xFezp8qybWigpg6WN5gkAuI39AIPdv4jdHijFU4_ns.jpg?fm=jpg&amp;s=70b7febedc4d774786e11226a4bbca8d
```
